openapi: 3.0.3
info:
  title: Swagger Movie archive - OpenAPI 3.0
  description: Basic movie archive API
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: movie
    description: Everything about your movies 
  - name : actors
    description: Everything about your actors
  - name: genre
    description: Everything about your movie genres
  - name: movieactors
    description: All the actors in your movies
  - name: moviegenre
    description: All the movies in chosen genre
paths:
  /movies:
    get:
      tags:
        - id
        - title
        - year
      summary: Finds all movies
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message : 
                    type: string
                  data : 
                    type: array
                    items: 
                      $ref: "#/components/schemas/movie"
                  
                required:
                  - message
                  - data
                additionalProperties: false  
        '400':
          description: Invalid status value
  /actors:
    get:
      tags:
        - id
        - name
      summary: Finds all actors
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: 
                    type: array
                    items:
                      $ref: "#/components/schemas/actors"
  /genre:
    get:
      tags:
        - id
        - genre
      summary: Finds all genres
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: 
                    type: array
                    items:
                      $ref: "#/components/schemas/genre"
  /moviesactor:
    get:
      tags:
        - id_movie
        - id_actors
      summary: Finds all actors of specified movie
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: 
                    type: array
                    items:
                      $ref: "#/components/schemas/moviesactor"
  /moviesgenre:
    get:
      tags:
        - id_movie
        - id_genre
      summary: Finds genre of specified movie
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: 
                    type: array
                    items:
                      $ref: "#/components/schemas/moviesgenre"
components:
  schemas:
    movie:
      type: object
      required:
        - id
        - title
        - year
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          description: Title of the movie
          example: "My first movie"
        year:
          type: integer
          format: int64
          example: 1990
      additionalProperties: false
    actors:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          description: Name of the actor
          example: "Emma Watson"
    genre:
      type: object
      required:
        - id
        - genre
      properties:
        id:
          type: integer
          format: int64
          example: 10
        genre:
          type: string
          description: Genre of the movie
          example: "Action"
    moviesactor:
      type: object
      required:
        - id_movie
        - id_actors
      properties:
        id_movie:
          type: integer
          format: int64
          example: 10
        id_actors:
          type: integer
          format: int64
          example: 10
    moviesgenre:
      type: object
      required:
        - id_movie
        - id_actors
      properties:
        id_movie:
          type: integer
          format: int64
          example: 10
        id_genre:
          type: integer
          format: int64
          example: 10