openapi: 3.0.3
info:
  title: Swagger Bookstore - OpenAPI 3.0
  description: Basic bookstore API
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: book
    description: Everything about your books
paths:
  /books:
    get:
      tags:
        - book
      summary: Finds all books
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message : 
                    type: string
                  data : 
                    type: array
                    items: 
                      $ref: "#/components/schemas/Book"
                  
                required:
                  - message
                  - data
                additionalProperties: false  
        '400':
          description: Invalid status value
components:
  schemas:
    Book:
      type: object
      required:
        - id
        - title
        - author
        - publish_year
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          description: Title of the book
          example: "My first book"
        author:
          type: string
          description: Author of the book
          example: "John Doe"
        publish_year:
          type: integer
          format: int64
          example: 1990
      additionalProperties: false